[package]
name = "plexo-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
uuid = { version = "1.5.0", features = ["v4"] }
thiserror = { version = "1.0.50", features = [] }
sqlx = { version = "0.7.2", features = ["postgres", "runtime-tokio", "tls-native-tls", "uuid", "chrono", "time"] }
tokio = { version = "1.34.0", features = ["full"] }
strum_macros = "0.25.3"
