[package]
name = "plexo-sdk"
version = "0.2.2"
edition = "2021"
description = "Plexo SDK"
license = "MIT OR Apache-2.0"

[dependencies]
chrono = "0.4.31"
uuid = { version = "1.5.0", features = ["v4"] }
thiserror = { version = "1.0.50", features = [] }
sqlx = { version = "0.7.2", features = [
    "postgres",
    "runtime-tokio",
    "tls-native-tls",
    "uuid",
    "chrono",
    "time",
] }
tokio = { version = "1.34.0", features = ["full"] }
strum_macros = "0.25.3"
strum = "0.25.0"
async-trait = "0.1.74"
derive_builder = "0.12.0"
dotenv = "0.15.0"
async-graphql = { version = "6.0.10", features = [
    "decimal",
    "chrono",
    "dataloader",
    "uuid",
] }
poem-openapi = { version = "3.0.5", features = [
    "swagger-ui",
    "chrono",
    "uuid",
] }
serde = "1.0.192"
